server:
  port: ${HTTP_SERVER_PORT:18010}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:18011}

spring:
  application:
    name: grpc-server
  threads:
    virtual:
      enabled: true


info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
