server:
  port: 18010

grpc:
  server:
    port: 18011

spring:
  application:
    name: grpc-server

  cloud:
    consul:
      host: ${REGISTER_SERVER_HOST:127.0.0.1}
      port: ${REGISTER_SERVER_PORT:8500}
      discovery:
        prefer-ip-address: true

info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
