// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

// Protobuf Java Version: 3.25.1
package com.xaaef.grpc.lib.pb;

public interface ClientInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xaaef.ClientInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 客户端 唯一认证 Id
   * </pre>
   *
   * <code>string clientId = 1;</code>
   * @return The clientId.
   */
  java.lang.String getClientId();
  /**
   * <pre>
   **
   * 客户端 唯一认证 Id
   * </pre>
   *
   * <code>string clientId = 1;</code>
   * @return The bytes for clientId.
   */
  com.google.protobuf.ByteString
      getClientIdBytes();

  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   **
   * 客户端 密钥
   * </pre>
   *
   * <code>string secret = 3;</code>
   * @return The secret.
   */
  java.lang.String getSecret();
  /**
   * <pre>
   **
   * 客户端 密钥
   * </pre>
   *
   * <code>string secret = 3;</code>
   * @return The bytes for secret.
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <pre>
   **
   * '客户端名称'
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   **
   * '客户端名称'
   * </pre>
   *
   * <code>string name = 4;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   **
   * 客户端 图标
   * </pre>
   *
   * <code>string logo = 5;</code>
   * @return The logo.
   */
  java.lang.String getLogo();
  /**
   * <pre>
   **
   * 客户端 图标
   * </pre>
   *
   * <code>string logo = 5;</code>
   * @return The bytes for logo.
   */
  com.google.protobuf.ByteString
      getLogoBytes();

  /**
   * <pre>
   **
   * 客户端 描述
   * </pre>
   *
   * <code>string description = 6;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   **
   * 客户端 描述
   * </pre>
   *
   * <code>string description = 6;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   **
   * 客户端类型 [ 0.第三方应用   1.系统内部应用 ]
   * </pre>
   *
   * <code>int32 clientType = 7;</code>
   * @return The clientType.
   */
  int getClientType();

  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   * @return A list containing the grantTypes.
   */
  java.util.List<java.lang.String>
      getGrantTypesList();
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   * @return The count of grantTypes.
   */
  int getGrantTypesCount();
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   * @param index The index of the element to return.
   * @return The grantTypes at the given index.
   */
  java.lang.String getGrantTypes(int index);
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   * @param index The index of the value to return.
   * @return The bytes of the grantTypes at the given index.
   */
  com.google.protobuf.ByteString
      getGrantTypesBytes(int index);

  /**
   * <pre>
   **
   * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
   * </pre>
   *
   * <code>string domainName = 9;</code>
   * @return The domainName.
   */
  java.lang.String getDomainName();
  /**
   * <pre>
   **
   * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
   * </pre>
   *
   * <code>string domainName = 9;</code>
   * @return The bytes for domainName.
   */
  com.google.protobuf.ByteString
      getDomainNameBytes();

  /**
   * <pre>
   **
   * 授权作用域
   * </pre>
   *
   * <code>string scope = 10;</code>
   * @return The scope.
   */
  java.lang.String getScope();
  /**
   * <pre>
   **
   * 授权作用域
   * </pre>
   *
   * <code>string scope = 10;</code>
   * @return The bytes for scope.
   */
  com.google.protobuf.ByteString
      getScopeBytes();
}
