// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

// Protobuf Java Version: 3.25.3
package com.xaaef.grpc.lib.pb;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xaaef.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
