// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

// Protobuf Java Version: 3.25.1
package com.xaaef.grpc.lib.pb;

public interface TokenInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xaaef.TokenInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 全局唯一认证 Id
   * </pre>
   *
   * <code>string tokenId = 1;</code>
   * @return The tokenId.
   */
  java.lang.String getTokenId();
  /**
   * <pre>
   **
   * 全局唯一认证 Id
   * </pre>
   *
   * <code>string tokenId = 1;</code>
   * @return The bytes for tokenId.
   */
  com.google.protobuf.ByteString
      getTokenIdBytes();

  /**
   * <pre>
   **
   * 认证授权方式
   * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>string grantType = 2;</code>
   * @return The grantType.
   */
  java.lang.String getGrantType();
  /**
   * <pre>
   **
   * 认证授权方式
   * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>string grantType = 2;</code>
   * @return The bytes for grantType.
   */
  com.google.protobuf.ByteString
      getGrantTypeBytes();

  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 3;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 3;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   **
   * 客户端信息
   * </pre>
   *
   * <code>.com.xaaef.ClientInfo loginClient = 4;</code>
   * @return Whether the loginClient field is set.
   */
  boolean hasLoginClient();
  /**
   * <pre>
   **
   * 客户端信息
   * </pre>
   *
   * <code>.com.xaaef.ClientInfo loginClient = 4;</code>
   * @return The loginClient.
   */
  com.xaaef.grpc.lib.pb.ClientInfo getLoginClient();
  /**
   * <pre>
   **
   * 客户端信息
   * </pre>
   *
   * <code>.com.xaaef.ClientInfo loginClient = 4;</code>
   */
  com.xaaef.grpc.lib.pb.ClientInfoOrBuilder getLoginClientOrBuilder();

  /**
   * <pre>
   **
   * 用户信息
   * </pre>
   *
   * <code>.com.xaaef.UserInfo loginUser = 5;</code>
   * @return Whether the loginUser field is set.
   */
  boolean hasLoginUser();
  /**
   * <pre>
   **
   * 用户信息
   * </pre>
   *
   * <code>.com.xaaef.UserInfo loginUser = 5;</code>
   * @return The loginUser.
   */
  com.xaaef.grpc.lib.pb.UserInfo getLoginUser();
  /**
   * <pre>
   **
   * 用户信息
   * </pre>
   *
   * <code>.com.xaaef.UserInfo loginUser = 5;</code>
   */
  com.xaaef.grpc.lib.pb.UserInfoOrBuilder getLoginUserOrBuilder();

  /**
   * <pre>
   **
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp loginTime = 6;</code>
   * @return Whether the loginTime field is set.
   */
  boolean hasLoginTime();
  /**
   * <pre>
   **
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp loginTime = 6;</code>
   * @return The loginTime.
   */
  com.google.protobuf.Timestamp getLoginTime();
  /**
   * <pre>
   **
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp loginTime = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLoginTimeOrBuilder();
}
