### hello
GET {{baseUrl}}/hello?name=tom
Content-Type: application/json


### howdy
GET {{baseUrl}}/howdy?name=alice
Content-Type: application/json


### getUserInfo
GET {{baseUrl}}/getUserInfo?name=jack
Content-Type: application/json



### getTokenInfo
GET {{baseUrl}}/getTokenInfo
Content-Type: application/json



### getLoginUser
GET {{baseUrl}}/getLoginUser
Content-Type: application/json


