### hello
GET {{baseUrl}}/hello?name=tom
Content-Type: application/json


### howdy
GET {{baseUrl}}/howdy?name=alice
Content-Type: application/json


### getUserInfo
GET {{baseUrl}}/getUserInfo?name=jack
Content-Type: application/json




### getString
GET {{baseUrl}}/getString?key=jack
Content-Type: application/json


### getBool
GET {{baseUrl}}/getBool?key=tom
Content-Type: application/json


### getNumber
GET {{baseUrl}}/getNumber?key=alice
Content-Type: application/json


