// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package com.xaaef.grpc.lib.domain;

/**
 * Protobuf type {@code com.xaaef.ClientInfo}
 */
public  final class ClientInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xaaef.ClientInfo)
    ClientInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ClientInfo.newBuilder() to construct.
  private ClientInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ClientInfo() {
    clientId_ = "";
    tenantId_ = "";
    secret_ = "";
    name_ = "";
    logo_ = "";
    description_ = "";
    clientType_ = 0;
    grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    domainName_ = "";
    scope_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ClientInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            clientId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tenantId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            secret_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            logo_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            description_ = s;
            break;
          }
          case 56: {

            clientType_ = input.readInt32();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
              grantTypes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000080;
            }
            grantTypes_.add(s);
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            domainName_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            scope_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
        grantTypes_ = grantTypes_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_ClientInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_ClientInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xaaef.grpc.lib.domain.ClientInfo.class, com.xaaef.grpc.lib.domain.ClientInfo.Builder.class);
  }

  private int bitField0_;
  public static final int CLIENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object clientId_;
  /**
   * <pre>
   **
   * 客户端 唯一认证 Id
   * </pre>
   *
   * <code>string clientId = 1;</code>
   */
  public java.lang.String getClientId() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      clientId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 客户端 唯一认证 Id
   * </pre>
   *
   * <code>string clientId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getClientIdBytes() {
    java.lang.Object ref = clientId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object tenantId_;
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   */
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECRET_FIELD_NUMBER = 3;
  private volatile java.lang.Object secret_;
  /**
   * <pre>
   **
   * 客户端 密钥
   * </pre>
   *
   * <code>string secret = 3;</code>
   */
  public java.lang.String getSecret() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secret_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 客户端 密钥
   * </pre>
   *
   * <code>string secret = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSecretBytes() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   **
   * '客户端名称'
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * '客户端名称'
   * </pre>
   *
   * <code>string name = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGO_FIELD_NUMBER = 5;
  private volatile java.lang.Object logo_;
  /**
   * <pre>
   **
   * 客户端 图标
   * </pre>
   *
   * <code>string logo = 5;</code>
   */
  public java.lang.String getLogo() {
    java.lang.Object ref = logo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 客户端 图标
   * </pre>
   *
   * <code>string logo = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLogoBytes() {
    java.lang.Object ref = logo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 6;
  private volatile java.lang.Object description_;
  /**
   * <pre>
   **
   * 客户端 描述
   * </pre>
   *
   * <code>string description = 6;</code>
   */
  public java.lang.String getDescription() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      description_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 客户端 描述
   * </pre>
   *
   * <code>string description = 6;</code>
   */
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    java.lang.Object ref = description_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      description_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLIENTTYPE_FIELD_NUMBER = 7;
  private int clientType_;
  /**
   * <pre>
   **
   * 客户端类型 [ 0.第三方应用   1.系统内部应用 ]
   * </pre>
   *
   * <code>int32 clientType = 7;</code>
   */
  public int getClientType() {
    return clientType_;
  }

  public static final int GRANTTYPES_FIELD_NUMBER = 8;
  private com.google.protobuf.LazyStringList grantTypes_;
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getGrantTypesList() {
    return grantTypes_;
  }
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   */
  public int getGrantTypesCount() {
    return grantTypes_.size();
  }
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   */
  public java.lang.String getGrantTypes(int index) {
    return grantTypes_.get(index);
  }
  /**
   * <pre>
   **
   * 授权类型 数组格式
   * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>repeated string grantTypes = 8;</code>
   */
  public com.google.protobuf.ByteString
      getGrantTypesBytes(int index) {
    return grantTypes_.getByteString(index);
  }

  public static final int DOMAINNAME_FIELD_NUMBER = 9;
  private volatile java.lang.Object domainName_;
  /**
   * <pre>
   **
   * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
   * </pre>
   *
   * <code>string domainName = 9;</code>
   */
  public java.lang.String getDomainName() {
    java.lang.Object ref = domainName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      domainName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
   * </pre>
   *
   * <code>string domainName = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDomainNameBytes() {
    java.lang.Object ref = domainName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      domainName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SCOPE_FIELD_NUMBER = 10;
  private volatile java.lang.Object scope_;
  /**
   * <pre>
   **
   * 授权作用域
   * </pre>
   *
   * <code>string scope = 10;</code>
   */
  public java.lang.String getScope() {
    java.lang.Object ref = scope_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      scope_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 授权作用域
   * </pre>
   *
   * <code>string scope = 10;</code>
   */
  public com.google.protobuf.ByteString
      getScopeBytes() {
    java.lang.Object ref = scope_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      scope_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getClientIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, clientId_);
    }
    if (!getTenantIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantId_);
    }
    if (!getSecretBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, secret_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
    }
    if (!getLogoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, logo_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, description_);
    }
    if (clientType_ != 0) {
      output.writeInt32(7, clientType_);
    }
    for (int i = 0; i < grantTypes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, grantTypes_.getRaw(i));
    }
    if (!getDomainNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, domainName_);
    }
    if (!getScopeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, scope_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getClientIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, clientId_);
    }
    if (!getTenantIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantId_);
    }
    if (!getSecretBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, secret_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
    }
    if (!getLogoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, logo_);
    }
    if (!getDescriptionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, description_);
    }
    if (clientType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, clientType_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < grantTypes_.size(); i++) {
        dataSize += computeStringSizeNoTag(grantTypes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getGrantTypesList().size();
    }
    if (!getDomainNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, domainName_);
    }
    if (!getScopeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, scope_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xaaef.grpc.lib.domain.ClientInfo)) {
      return super.equals(obj);
    }
    com.xaaef.grpc.lib.domain.ClientInfo other = (com.xaaef.grpc.lib.domain.ClientInfo) obj;

    boolean result = true;
    result = result && getClientId()
        .equals(other.getClientId());
    result = result && getTenantId()
        .equals(other.getTenantId());
    result = result && getSecret()
        .equals(other.getSecret());
    result = result && getName()
        .equals(other.getName());
    result = result && getLogo()
        .equals(other.getLogo());
    result = result && getDescription()
        .equals(other.getDescription());
    result = result && (getClientType()
        == other.getClientType());
    result = result && getGrantTypesList()
        .equals(other.getGrantTypesList());
    result = result && getDomainName()
        .equals(other.getDomainName());
    result = result && getScope()
        .equals(other.getScope());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
    hash = (53 * hash) + getClientId().hashCode();
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSecret().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + LOGO_FIELD_NUMBER;
    hash = (53 * hash) + getLogo().hashCode();
    hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
    hash = (53 * hash) + getDescription().hashCode();
    hash = (37 * hash) + CLIENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getClientType();
    if (getGrantTypesCount() > 0) {
      hash = (37 * hash) + GRANTTYPES_FIELD_NUMBER;
      hash = (53 * hash) + getGrantTypesList().hashCode();
    }
    hash = (37 * hash) + DOMAINNAME_FIELD_NUMBER;
    hash = (53 * hash) + getDomainName().hashCode();
    hash = (37 * hash) + SCOPE_FIELD_NUMBER;
    hash = (53 * hash) + getScope().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.ClientInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xaaef.grpc.lib.domain.ClientInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xaaef.ClientInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xaaef.ClientInfo)
      com.xaaef.grpc.lib.domain.ClientInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_ClientInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_ClientInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xaaef.grpc.lib.domain.ClientInfo.class, com.xaaef.grpc.lib.domain.ClientInfo.Builder.class);
    }

    // Construct using com.xaaef.grpc.lib.domain.ClientInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      clientId_ = "";

      tenantId_ = "";

      secret_ = "";

      name_ = "";

      logo_ = "";

      description_ = "";

      clientType_ = 0;

      grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      domainName_ = "";

      scope_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_ClientInfo_descriptor;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.ClientInfo getDefaultInstanceForType() {
      return com.xaaef.grpc.lib.domain.ClientInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.ClientInfo build() {
      com.xaaef.grpc.lib.domain.ClientInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.ClientInfo buildPartial() {
      com.xaaef.grpc.lib.domain.ClientInfo result = new com.xaaef.grpc.lib.domain.ClientInfo(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.clientId_ = clientId_;
      result.tenantId_ = tenantId_;
      result.secret_ = secret_;
      result.name_ = name_;
      result.logo_ = logo_;
      result.description_ = description_;
      result.clientType_ = clientType_;
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        grantTypes_ = grantTypes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000080);
      }
      result.grantTypes_ = grantTypes_;
      result.domainName_ = domainName_;
      result.scope_ = scope_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xaaef.grpc.lib.domain.ClientInfo) {
        return mergeFrom((com.xaaef.grpc.lib.domain.ClientInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xaaef.grpc.lib.domain.ClientInfo other) {
      if (other == com.xaaef.grpc.lib.domain.ClientInfo.getDefaultInstance()) return this;
      if (!other.getClientId().isEmpty()) {
        clientId_ = other.clientId_;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (!other.getSecret().isEmpty()) {
        secret_ = other.secret_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getLogo().isEmpty()) {
        logo_ = other.logo_;
        onChanged();
      }
      if (!other.getDescription().isEmpty()) {
        description_ = other.description_;
        onChanged();
      }
      if (other.getClientType() != 0) {
        setClientType(other.getClientType());
      }
      if (!other.grantTypes_.isEmpty()) {
        if (grantTypes_.isEmpty()) {
          grantTypes_ = other.grantTypes_;
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          ensureGrantTypesIsMutable();
          grantTypes_.addAll(other.grantTypes_);
        }
        onChanged();
      }
      if (!other.getDomainName().isEmpty()) {
        domainName_ = other.domainName_;
        onChanged();
      }
      if (!other.getScope().isEmpty()) {
        scope_ = other.scope_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xaaef.grpc.lib.domain.ClientInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xaaef.grpc.lib.domain.ClientInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object clientId_ = "";
    /**
     * <pre>
     **
     * 客户端 唯一认证 Id
     * </pre>
     *
     * <code>string clientId = 1;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 唯一认证 Id
     * </pre>
     *
     * <code>string clientId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 唯一认证 Id
     * </pre>
     *
     * <code>string clientId = 1;</code>
     */
    public Builder setClientId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      clientId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 唯一认证 Id
     * </pre>
     *
     * <code>string clientId = 1;</code>
     */
    public Builder clearClientId() {
      
      clientId_ = getDefaultInstance().getClientId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 唯一认证 Id
     * </pre>
     *
     * <code>string clientId = 1;</code>
     */
    public Builder setClientIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      clientId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object secret_ = "";
    /**
     * <pre>
     **
     * 客户端 密钥
     * </pre>
     *
     * <code>string secret = 3;</code>
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 密钥
     * </pre>
     *
     * <code>string secret = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 密钥
     * </pre>
     *
     * <code>string secret = 3;</code>
     */
    public Builder setSecret(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      secret_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 密钥
     * </pre>
     *
     * <code>string secret = 3;</code>
     */
    public Builder clearSecret() {
      
      secret_ = getDefaultInstance().getSecret();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 密钥
     * </pre>
     *
     * <code>string secret = 3;</code>
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      secret_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     **
     * '客户端名称'
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * '客户端名称'
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * '客户端名称'
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * '客户端名称'
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * '客户端名称'
     * </pre>
     *
     * <code>string name = 4;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object logo_ = "";
    /**
     * <pre>
     **
     * 客户端 图标
     * </pre>
     *
     * <code>string logo = 5;</code>
     */
    public java.lang.String getLogo() {
      java.lang.Object ref = logo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 图标
     * </pre>
     *
     * <code>string logo = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLogoBytes() {
      java.lang.Object ref = logo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 图标
     * </pre>
     *
     * <code>string logo = 5;</code>
     */
    public Builder setLogo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      logo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 图标
     * </pre>
     *
     * <code>string logo = 5;</code>
     */
    public Builder clearLogo() {
      
      logo_ = getDefaultInstance().getLogo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 图标
     * </pre>
     *
     * <code>string logo = 5;</code>
     */
    public Builder setLogoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      logo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object description_ = "";
    /**
     * <pre>
     **
     * 客户端 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 客户端 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public Builder setDescription(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      description_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public Builder clearDescription() {
      
      description_ = getDefaultInstance().getDescription();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端 描述
     * </pre>
     *
     * <code>string description = 6;</code>
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      description_ = value;
      onChanged();
      return this;
    }

    private int clientType_ ;
    /**
     * <pre>
     **
     * 客户端类型 [ 0.第三方应用   1.系统内部应用 ]
     * </pre>
     *
     * <code>int32 clientType = 7;</code>
     */
    public int getClientType() {
      return clientType_;
    }
    /**
     * <pre>
     **
     * 客户端类型 [ 0.第三方应用   1.系统内部应用 ]
     * </pre>
     *
     * <code>int32 clientType = 7;</code>
     */
    public Builder setClientType(int value) {
      
      clientType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 客户端类型 [ 0.第三方应用   1.系统内部应用 ]
     * </pre>
     *
     * <code>int32 clientType = 7;</code>
     */
    public Builder clearClientType() {
      
      clientType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureGrantTypesIsMutable() {
      if (!((bitField0_ & 0x00000080) == 0x00000080)) {
        grantTypes_ = new com.google.protobuf.LazyStringArrayList(grantTypes_);
        bitField0_ |= 0x00000080;
       }
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getGrantTypesList() {
      return grantTypes_.getUnmodifiableView();
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public int getGrantTypesCount() {
      return grantTypes_.size();
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public java.lang.String getGrantTypes(int index) {
      return grantTypes_.get(index);
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public com.google.protobuf.ByteString
        getGrantTypesBytes(int index) {
      return grantTypes_.getByteString(index);
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public Builder setGrantTypes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGrantTypesIsMutable();
      grantTypes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public Builder addGrantTypes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureGrantTypesIsMutable();
      grantTypes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public Builder addAllGrantTypes(
        java.lang.Iterable<java.lang.String> values) {
      ensureGrantTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, grantTypes_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public Builder clearGrantTypes() {
      grantTypes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000080);
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 授权类型 数组格式
     * 授权类型，必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>repeated string grantTypes = 8;</code>
     */
    public Builder addGrantTypesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureGrantTypesIsMutable();
      grantTypes_.add(value);
      onChanged();
      return this;
    }

    private java.lang.Object domainName_ = "";
    /**
     * <pre>
     **
     * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
     * </pre>
     *
     * <code>string domainName = 9;</code>
     */
    public java.lang.String getDomainName() {
      java.lang.Object ref = domainName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        domainName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
     * </pre>
     *
     * <code>string domainName = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDomainNameBytes() {
      java.lang.Object ref = domainName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        domainName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
     * </pre>
     *
     * <code>string domainName = 9;</code>
     */
    public Builder setDomainName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      domainName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
     * </pre>
     *
     * <code>string domainName = 9;</code>
     */
    public Builder clearDomainName() {
      
      domainName_ = getDefaultInstance().getDomainName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 域名地址，如果是 授权码模式， 必须校验回调地址是否属于此域名之下
     * </pre>
     *
     * <code>string domainName = 9;</code>
     */
    public Builder setDomainNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      domainName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object scope_ = "";
    /**
     * <pre>
     **
     * 授权作用域
     * </pre>
     *
     * <code>string scope = 10;</code>
     */
    public java.lang.String getScope() {
      java.lang.Object ref = scope_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        scope_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 授权作用域
     * </pre>
     *
     * <code>string scope = 10;</code>
     */
    public com.google.protobuf.ByteString
        getScopeBytes() {
      java.lang.Object ref = scope_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        scope_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 授权作用域
     * </pre>
     *
     * <code>string scope = 10;</code>
     */
    public Builder setScope(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      scope_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 授权作用域
     * </pre>
     *
     * <code>string scope = 10;</code>
     */
    public Builder clearScope() {
      
      scope_ = getDefaultInstance().getScope();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 授权作用域
     * </pre>
     *
     * <code>string scope = 10;</code>
     */
    public Builder setScopeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      scope_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xaaef.ClientInfo)
  }

  // @@protoc_insertion_point(class_scope:com.xaaef.ClientInfo)
  private static final com.xaaef.grpc.lib.domain.ClientInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xaaef.grpc.lib.domain.ClientInfo();
  }

  public static com.xaaef.grpc.lib.domain.ClientInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ClientInfo>
      PARSER = new com.google.protobuf.AbstractParser<ClientInfo>() {
    @java.lang.Override
    public ClientInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ClientInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ClientInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ClientInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xaaef.grpc.lib.domain.ClientInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

