// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package com.xaaef.grpc.lib.domain;

/**
 * Protobuf type {@code greet.TokenInfo}
 */
public final class TokenInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:greet.TokenInfo)
    TokenInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TokenInfo.newBuilder() to construct.
  private TokenInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TokenInfo() {
    tokenId_ = "";
    grantType_ = "";
    tenantId_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new TokenInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_TokenInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_TokenInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xaaef.grpc.lib.domain.TokenInfo.class, com.xaaef.grpc.lib.domain.TokenInfo.Builder.class);
  }

  public static final int TOKENID_FIELD_NUMBER = 1;
  private volatile java.lang.Object tokenId_;
  /**
   * <pre>
   **
   * 全局唯一认证 Id
   * </pre>
   *
   * <code>string tokenId = 1;</code>
   * @return The tokenId.
   */
  @java.lang.Override
  public java.lang.String getTokenId() {
    java.lang.Object ref = tokenId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tokenId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 全局唯一认证 Id
   * </pre>
   *
   * <code>string tokenId = 1;</code>
   * @return The bytes for tokenId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTokenIdBytes() {
    java.lang.Object ref = tokenId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tokenId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GRANTTYPE_FIELD_NUMBER = 2;
  private volatile java.lang.Object grantType_;
  /**
   * <pre>
   **
   * 认证授权方式
   * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>string grantType = 2;</code>
   * @return The grantType.
   */
  @java.lang.Override
  public java.lang.String getGrantType() {
    java.lang.Object ref = grantType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      grantType_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 认证授权方式
   * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
   * </pre>
   *
   * <code>string grantType = 2;</code>
   * @return The bytes for grantType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGrantTypeBytes() {
    java.lang.Object ref = grantType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      grantType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TENANTID_FIELD_NUMBER = 3;
  private volatile java.lang.Object tenantId_;
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 3;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 3;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGINCLIENT_FIELD_NUMBER = 4;
  private com.xaaef.grpc.lib.domain.ClientInfo loginClient_;
  /**
   * <pre>
   **
   * 客户端信息
   * </pre>
   *
   * <code>.greet.ClientInfo loginClient = 4;</code>
   * @return Whether the loginClient field is set.
   */
  @java.lang.Override
  public boolean hasLoginClient() {
    return loginClient_ != null;
  }
  /**
   * <pre>
   **
   * 客户端信息
   * </pre>
   *
   * <code>.greet.ClientInfo loginClient = 4;</code>
   * @return The loginClient.
   */
  @java.lang.Override
  public com.xaaef.grpc.lib.domain.ClientInfo getLoginClient() {
    return loginClient_ == null ? com.xaaef.grpc.lib.domain.ClientInfo.getDefaultInstance() : loginClient_;
  }
  /**
   * <pre>
   **
   * 客户端信息
   * </pre>
   *
   * <code>.greet.ClientInfo loginClient = 4;</code>
   */
  @java.lang.Override
  public com.xaaef.grpc.lib.domain.ClientInfoOrBuilder getLoginClientOrBuilder() {
    return getLoginClient();
  }

  public static final int LOGINUSER_FIELD_NUMBER = 5;
  private com.xaaef.grpc.lib.domain.UserInfo loginUser_;
  /**
   * <pre>
   **
   * 用户信息
   * </pre>
   *
   * <code>.greet.UserInfo loginUser = 5;</code>
   * @return Whether the loginUser field is set.
   */
  @java.lang.Override
  public boolean hasLoginUser() {
    return loginUser_ != null;
  }
  /**
   * <pre>
   **
   * 用户信息
   * </pre>
   *
   * <code>.greet.UserInfo loginUser = 5;</code>
   * @return The loginUser.
   */
  @java.lang.Override
  public com.xaaef.grpc.lib.domain.UserInfo getLoginUser() {
    return loginUser_ == null ? com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance() : loginUser_;
  }
  /**
   * <pre>
   **
   * 用户信息
   * </pre>
   *
   * <code>.greet.UserInfo loginUser = 5;</code>
   */
  @java.lang.Override
  public com.xaaef.grpc.lib.domain.UserInfoOrBuilder getLoginUserOrBuilder() {
    return getLoginUser();
  }

  public static final int LOGINTIME_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp loginTime_;
  /**
   * <pre>
   **
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp loginTime = 6;</code>
   * @return Whether the loginTime field is set.
   */
  @java.lang.Override
  public boolean hasLoginTime() {
    return loginTime_ != null;
  }
  /**
   * <pre>
   **
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp loginTime = 6;</code>
   * @return The loginTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getLoginTime() {
    return loginTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : loginTime_;
  }
  /**
   * <pre>
   **
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Timestamp loginTime = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getLoginTimeOrBuilder() {
    return getLoginTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tokenId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(grantType_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, grantType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, tenantId_);
    }
    if (loginClient_ != null) {
      output.writeMessage(4, getLoginClient());
    }
    if (loginUser_ != null) {
      output.writeMessage(5, getLoginUser());
    }
    if (loginTime_ != null) {
      output.writeMessage(6, getLoginTime());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tokenId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tokenId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(grantType_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, grantType_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, tenantId_);
    }
    if (loginClient_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getLoginClient());
    }
    if (loginUser_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLoginUser());
    }
    if (loginTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getLoginTime());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xaaef.grpc.lib.domain.TokenInfo)) {
      return super.equals(obj);
    }
    com.xaaef.grpc.lib.domain.TokenInfo other = (com.xaaef.grpc.lib.domain.TokenInfo) obj;

    if (!getTokenId()
        .equals(other.getTokenId())) return false;
    if (!getGrantType()
        .equals(other.getGrantType())) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (hasLoginClient() != other.hasLoginClient()) return false;
    if (hasLoginClient()) {
      if (!getLoginClient()
          .equals(other.getLoginClient())) return false;
    }
    if (hasLoginUser() != other.hasLoginUser()) return false;
    if (hasLoginUser()) {
      if (!getLoginUser()
          .equals(other.getLoginUser())) return false;
    }
    if (hasLoginTime() != other.hasLoginTime()) return false;
    if (hasLoginTime()) {
      if (!getLoginTime()
          .equals(other.getLoginTime())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOKENID_FIELD_NUMBER;
    hash = (53 * hash) + getTokenId().hashCode();
    hash = (37 * hash) + GRANTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getGrantType().hashCode();
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    if (hasLoginClient()) {
      hash = (37 * hash) + LOGINCLIENT_FIELD_NUMBER;
      hash = (53 * hash) + getLoginClient().hashCode();
    }
    if (hasLoginUser()) {
      hash = (37 * hash) + LOGINUSER_FIELD_NUMBER;
      hash = (53 * hash) + getLoginUser().hashCode();
    }
    if (hasLoginTime()) {
      hash = (37 * hash) + LOGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginTime().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.TokenInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xaaef.grpc.lib.domain.TokenInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code greet.TokenInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:greet.TokenInfo)
      com.xaaef.grpc.lib.domain.TokenInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_TokenInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_TokenInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xaaef.grpc.lib.domain.TokenInfo.class, com.xaaef.grpc.lib.domain.TokenInfo.Builder.class);
    }

    // Construct using com.xaaef.grpc.lib.domain.TokenInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tokenId_ = "";

      grantType_ = "";

      tenantId_ = "";

      if (loginClientBuilder_ == null) {
        loginClient_ = null;
      } else {
        loginClient_ = null;
        loginClientBuilder_ = null;
      }
      if (loginUserBuilder_ == null) {
        loginUser_ = null;
      } else {
        loginUser_ = null;
        loginUserBuilder_ = null;
      }
      if (loginTimeBuilder_ == null) {
        loginTime_ = null;
      } else {
        loginTime_ = null;
        loginTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_TokenInfo_descriptor;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.TokenInfo getDefaultInstanceForType() {
      return com.xaaef.grpc.lib.domain.TokenInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.TokenInfo build() {
      com.xaaef.grpc.lib.domain.TokenInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.TokenInfo buildPartial() {
      com.xaaef.grpc.lib.domain.TokenInfo result = new com.xaaef.grpc.lib.domain.TokenInfo(this);
      result.tokenId_ = tokenId_;
      result.grantType_ = grantType_;
      result.tenantId_ = tenantId_;
      if (loginClientBuilder_ == null) {
        result.loginClient_ = loginClient_;
      } else {
        result.loginClient_ = loginClientBuilder_.build();
      }
      if (loginUserBuilder_ == null) {
        result.loginUser_ = loginUser_;
      } else {
        result.loginUser_ = loginUserBuilder_.build();
      }
      if (loginTimeBuilder_ == null) {
        result.loginTime_ = loginTime_;
      } else {
        result.loginTime_ = loginTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xaaef.grpc.lib.domain.TokenInfo) {
        return mergeFrom((com.xaaef.grpc.lib.domain.TokenInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xaaef.grpc.lib.domain.TokenInfo other) {
      if (other == com.xaaef.grpc.lib.domain.TokenInfo.getDefaultInstance()) return this;
      if (!other.getTokenId().isEmpty()) {
        tokenId_ = other.tokenId_;
        onChanged();
      }
      if (!other.getGrantType().isEmpty()) {
        grantType_ = other.grantType_;
        onChanged();
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (other.hasLoginClient()) {
        mergeLoginClient(other.getLoginClient());
      }
      if (other.hasLoginUser()) {
        mergeLoginUser(other.getLoginUser());
      }
      if (other.hasLoginTime()) {
        mergeLoginTime(other.getLoginTime());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              tokenId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 18: {
              grantType_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              tenantId_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getLoginClientFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 34
            case 42: {
              input.readMessage(
                  getLoginUserFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getLoginTimeFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object tokenId_ = "";
    /**
     * <pre>
     **
     * 全局唯一认证 Id
     * </pre>
     *
     * <code>string tokenId = 1;</code>
     * @return The tokenId.
     */
    public java.lang.String getTokenId() {
      java.lang.Object ref = tokenId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 全局唯一认证 Id
     * </pre>
     *
     * <code>string tokenId = 1;</code>
     * @return The bytes for tokenId.
     */
    public com.google.protobuf.ByteString
        getTokenIdBytes() {
      java.lang.Object ref = tokenId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 全局唯一认证 Id
     * </pre>
     *
     * <code>string tokenId = 1;</code>
     * @param value The tokenId to set.
     * @return This builder for chaining.
     */
    public Builder setTokenId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tokenId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 全局唯一认证 Id
     * </pre>
     *
     * <code>string tokenId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTokenId() {
      
      tokenId_ = getDefaultInstance().getTokenId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 全局唯一认证 Id
     * </pre>
     *
     * <code>string tokenId = 1;</code>
     * @param value The bytes for tokenId to set.
     * @return This builder for chaining.
     */
    public Builder setTokenIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tokenId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object grantType_ = "";
    /**
     * <pre>
     **
     * 认证授权方式
     * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>string grantType = 2;</code>
     * @return The grantType.
     */
    public java.lang.String getGrantType() {
      java.lang.Object ref = grantType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        grantType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 认证授权方式
     * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>string grantType = 2;</code>
     * @return The bytes for grantType.
     */
    public com.google.protobuf.ByteString
        getGrantTypeBytes() {
      java.lang.Object ref = grantType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        grantType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 认证授权方式
     * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>string grantType = 2;</code>
     * @param value The grantType to set.
     * @return This builder for chaining.
     */
    public Builder setGrantType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      grantType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 认证授权方式
     * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>string grantType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGrantType() {
      
      grantType_ = getDefaultInstance().getGrantType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 认证授权方式
     * 必须是[ authorization_code | password | client_credentials | tencent_qq | we_chat | sms ]之一！
     * </pre>
     *
     * <code>string grantType = 2;</code>
     * @param value The bytes for grantType to set.
     * @return This builder for chaining.
     */
    public Builder setGrantTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      grantType_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 3;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 3;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 3;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 3;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private com.xaaef.grpc.lib.domain.ClientInfo loginClient_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xaaef.grpc.lib.domain.ClientInfo, com.xaaef.grpc.lib.domain.ClientInfo.Builder, com.xaaef.grpc.lib.domain.ClientInfoOrBuilder> loginClientBuilder_;
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     * @return Whether the loginClient field is set.
     */
    public boolean hasLoginClient() {
      return loginClientBuilder_ != null || loginClient_ != null;
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     * @return The loginClient.
     */
    public com.xaaef.grpc.lib.domain.ClientInfo getLoginClient() {
      if (loginClientBuilder_ == null) {
        return loginClient_ == null ? com.xaaef.grpc.lib.domain.ClientInfo.getDefaultInstance() : loginClient_;
      } else {
        return loginClientBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    public Builder setLoginClient(com.xaaef.grpc.lib.domain.ClientInfo value) {
      if (loginClientBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginClient_ = value;
        onChanged();
      } else {
        loginClientBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    public Builder setLoginClient(
        com.xaaef.grpc.lib.domain.ClientInfo.Builder builderForValue) {
      if (loginClientBuilder_ == null) {
        loginClient_ = builderForValue.build();
        onChanged();
      } else {
        loginClientBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    public Builder mergeLoginClient(com.xaaef.grpc.lib.domain.ClientInfo value) {
      if (loginClientBuilder_ == null) {
        if (loginClient_ != null) {
          loginClient_ =
            com.xaaef.grpc.lib.domain.ClientInfo.newBuilder(loginClient_).mergeFrom(value).buildPartial();
        } else {
          loginClient_ = value;
        }
        onChanged();
      } else {
        loginClientBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    public Builder clearLoginClient() {
      if (loginClientBuilder_ == null) {
        loginClient_ = null;
        onChanged();
      } else {
        loginClient_ = null;
        loginClientBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    public com.xaaef.grpc.lib.domain.ClientInfo.Builder getLoginClientBuilder() {
      
      onChanged();
      return getLoginClientFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    public com.xaaef.grpc.lib.domain.ClientInfoOrBuilder getLoginClientOrBuilder() {
      if (loginClientBuilder_ != null) {
        return loginClientBuilder_.getMessageOrBuilder();
      } else {
        return loginClient_ == null ?
            com.xaaef.grpc.lib.domain.ClientInfo.getDefaultInstance() : loginClient_;
      }
    }
    /**
     * <pre>
     **
     * 客户端信息
     * </pre>
     *
     * <code>.greet.ClientInfo loginClient = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xaaef.grpc.lib.domain.ClientInfo, com.xaaef.grpc.lib.domain.ClientInfo.Builder, com.xaaef.grpc.lib.domain.ClientInfoOrBuilder> 
        getLoginClientFieldBuilder() {
      if (loginClientBuilder_ == null) {
        loginClientBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xaaef.grpc.lib.domain.ClientInfo, com.xaaef.grpc.lib.domain.ClientInfo.Builder, com.xaaef.grpc.lib.domain.ClientInfoOrBuilder>(
                getLoginClient(),
                getParentForChildren(),
                isClean());
        loginClient_ = null;
      }
      return loginClientBuilder_;
    }

    private com.xaaef.grpc.lib.domain.UserInfo loginUser_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xaaef.grpc.lib.domain.UserInfo, com.xaaef.grpc.lib.domain.UserInfo.Builder, com.xaaef.grpc.lib.domain.UserInfoOrBuilder> loginUserBuilder_;
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     * @return Whether the loginUser field is set.
     */
    public boolean hasLoginUser() {
      return loginUserBuilder_ != null || loginUser_ != null;
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     * @return The loginUser.
     */
    public com.xaaef.grpc.lib.domain.UserInfo getLoginUser() {
      if (loginUserBuilder_ == null) {
        return loginUser_ == null ? com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance() : loginUser_;
      } else {
        return loginUserBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    public Builder setLoginUser(com.xaaef.grpc.lib.domain.UserInfo value) {
      if (loginUserBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginUser_ = value;
        onChanged();
      } else {
        loginUserBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    public Builder setLoginUser(
        com.xaaef.grpc.lib.domain.UserInfo.Builder builderForValue) {
      if (loginUserBuilder_ == null) {
        loginUser_ = builderForValue.build();
        onChanged();
      } else {
        loginUserBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    public Builder mergeLoginUser(com.xaaef.grpc.lib.domain.UserInfo value) {
      if (loginUserBuilder_ == null) {
        if (loginUser_ != null) {
          loginUser_ =
            com.xaaef.grpc.lib.domain.UserInfo.newBuilder(loginUser_).mergeFrom(value).buildPartial();
        } else {
          loginUser_ = value;
        }
        onChanged();
      } else {
        loginUserBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    public Builder clearLoginUser() {
      if (loginUserBuilder_ == null) {
        loginUser_ = null;
        onChanged();
      } else {
        loginUser_ = null;
        loginUserBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    public com.xaaef.grpc.lib.domain.UserInfo.Builder getLoginUserBuilder() {
      
      onChanged();
      return getLoginUserFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    public com.xaaef.grpc.lib.domain.UserInfoOrBuilder getLoginUserOrBuilder() {
      if (loginUserBuilder_ != null) {
        return loginUserBuilder_.getMessageOrBuilder();
      } else {
        return loginUser_ == null ?
            com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance() : loginUser_;
      }
    }
    /**
     * <pre>
     **
     * 用户信息
     * </pre>
     *
     * <code>.greet.UserInfo loginUser = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.xaaef.grpc.lib.domain.UserInfo, com.xaaef.grpc.lib.domain.UserInfo.Builder, com.xaaef.grpc.lib.domain.UserInfoOrBuilder> 
        getLoginUserFieldBuilder() {
      if (loginUserBuilder_ == null) {
        loginUserBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.xaaef.grpc.lib.domain.UserInfo, com.xaaef.grpc.lib.domain.UserInfo.Builder, com.xaaef.grpc.lib.domain.UserInfoOrBuilder>(
                getLoginUser(),
                getParentForChildren(),
                isClean());
        loginUser_ = null;
      }
      return loginUserBuilder_;
    }

    private com.google.protobuf.Timestamp loginTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> loginTimeBuilder_;
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     * @return Whether the loginTime field is set.
     */
    public boolean hasLoginTime() {
      return loginTimeBuilder_ != null || loginTime_ != null;
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     * @return The loginTime.
     */
    public com.google.protobuf.Timestamp getLoginTime() {
      if (loginTimeBuilder_ == null) {
        return loginTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : loginTime_;
      } else {
        return loginTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    public Builder setLoginTime(com.google.protobuf.Timestamp value) {
      if (loginTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginTime_ = value;
        onChanged();
      } else {
        loginTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    public Builder setLoginTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (loginTimeBuilder_ == null) {
        loginTime_ = builderForValue.build();
        onChanged();
      } else {
        loginTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    public Builder mergeLoginTime(com.google.protobuf.Timestamp value) {
      if (loginTimeBuilder_ == null) {
        if (loginTime_ != null) {
          loginTime_ =
            com.google.protobuf.Timestamp.newBuilder(loginTime_).mergeFrom(value).buildPartial();
        } else {
          loginTime_ = value;
        }
        onChanged();
      } else {
        loginTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    public Builder clearLoginTime() {
      if (loginTimeBuilder_ == null) {
        loginTime_ = null;
        onChanged();
      } else {
        loginTime_ = null;
        loginTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getLoginTimeBuilder() {
      
      onChanged();
      return getLoginTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getLoginTimeOrBuilder() {
      if (loginTimeBuilder_ != null) {
        return loginTimeBuilder_.getMessageOrBuilder();
      } else {
        return loginTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : loginTime_;
      }
    }
    /**
     * <pre>
     **
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Timestamp loginTime = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getLoginTimeFieldBuilder() {
      if (loginTimeBuilder_ == null) {
        loginTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getLoginTime(),
                getParentForChildren(),
                isClean());
        loginTime_ = null;
      }
      return loginTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:greet.TokenInfo)
  }

  // @@protoc_insertion_point(class_scope:greet.TokenInfo)
  private static final com.xaaef.grpc.lib.domain.TokenInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xaaef.grpc.lib.domain.TokenInfo();
  }

  public static com.xaaef.grpc.lib.domain.TokenInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TokenInfo>
      PARSER = new com.google.protobuf.AbstractParser<TokenInfo>() {
    @java.lang.Override
    public TokenInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TokenInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TokenInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xaaef.grpc.lib.domain.TokenInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

