// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package com.xaaef.grpc.lib.domain;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();

  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   * @return The avatar.
   */
  java.lang.String getAvatar();
  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   * @return The bytes for avatar.
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   * @return The mobile.
   */
  java.lang.String getMobile();
  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   * @return The bytes for mobile.
   */
  com.google.protobuf.ByteString
      getMobileBytes();

  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   * @return The nickname.
   */
  java.lang.String getNickname();
  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   * @return The bytes for nickname.
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   **
   * 性别[ 0.女  1.男  2.未知]
   * </pre>
   *
   * <code>int32 gender = 9;</code>
   * @return The gender.
   */
  int getGender();

  /**
   * <pre>
   **
   * 用户类型 0.租户用户 1. 系统用户
   * </pre>
   *
   * <code>int32 userType = 10;</code>
   * @return The userType.
   */
  int getUserType();

  /**
   * <pre>
   **
   * 所属部门
   * </pre>
   *
   * <code>int64 deptId = 11;</code>
   * @return The deptId.
   */
  long getDeptId();

  /**
   * <pre>
   **
   * 状态 【0.禁用 1.正常】
   * </pre>
   *
   * <code>int32 status = 12;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <pre>
   **
   * 是否管理员 0. 普通用户  1. 管理员
   * </pre>
   *
   * <code>int32 adminFlag = 13;</code>
   * @return The adminFlag.
   */
  int getAdminFlag();

  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   * @return Whether the expired field is set.
   */
  boolean hasExpired();
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   * @return The expired.
   */
  com.google.protobuf.Timestamp getExpired();
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiredOrBuilder();
}
