// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package com.xaaef.grpc.lib.domain;

/**
 * Protobuf type {@code com.xaaef.UserInfo}
 */
public  final class UserInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.xaaef.UserInfo)
    UserInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserInfo.newBuilder() to construct.
  private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserInfo() {
    userId_ = 0L;
    tenantId_ = "";
    avatar_ = "";
    username_ = "";
    mobile_ = "";
    email_ = "";
    nickname_ = "";
    password_ = "";
    gender_ = 0;
    userType_ = 0;
    deptId_ = 0L;
    status_ = 0;
    adminFlag_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private UserInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            tenantId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            avatar_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            mobile_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            nickname_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            password_ = s;
            break;
          }
          case 72: {

            gender_ = input.readInt32();
            break;
          }
          case 80: {

            userType_ = input.readInt32();
            break;
          }
          case 88: {

            deptId_ = input.readInt64();
            break;
          }
          case 96: {

            status_ = input.readInt32();
            break;
          }
          case 104: {

            adminFlag_ = input.readInt32();
            break;
          }
          case 114: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (expired_ != null) {
              subBuilder = expired_.toBuilder();
            }
            expired_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(expired_);
              expired_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_UserInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_UserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xaaef.grpc.lib.domain.UserInfo.class, com.xaaef.grpc.lib.domain.UserInfo.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   */
  public long getUserId() {
    return userId_;
  }

  public static final int TENANTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object tenantId_;
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   */
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object avatar_;
  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object username_;
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOBILE_FIELD_NUMBER = 5;
  private volatile java.lang.Object mobile_;
  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   */
  public java.lang.String getMobile() {
    java.lang.Object ref = mobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mobile_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   */
  public com.google.protobuf.ByteString
      getMobileBytes() {
    java.lang.Object ref = mobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object nickname_;
  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   */
  public java.lang.String getNickname() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nickname_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   */
  public com.google.protobuf.ByteString
      getNicknameBytes() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 8;
  private volatile java.lang.Object password_;
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   */
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   */
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 9;
  private int gender_;
  /**
   * <pre>
   **
   * 性别[ 0.女  1.男  2.未知]
   * </pre>
   *
   * <code>int32 gender = 9;</code>
   */
  public int getGender() {
    return gender_;
  }

  public static final int USERTYPE_FIELD_NUMBER = 10;
  private int userType_;
  /**
   * <pre>
   **
   * 用户类型 0.租户用户 1. 系统用户
   * </pre>
   *
   * <code>int32 userType = 10;</code>
   */
  public int getUserType() {
    return userType_;
  }

  public static final int DEPTID_FIELD_NUMBER = 11;
  private long deptId_;
  /**
   * <pre>
   **
   * 所属部门
   * </pre>
   *
   * <code>int64 deptId = 11;</code>
   */
  public long getDeptId() {
    return deptId_;
  }

  public static final int STATUS_FIELD_NUMBER = 12;
  private int status_;
  /**
   * <pre>
   **
   * 状态 【0.禁用 1.正常】
   * </pre>
   *
   * <code>int32 status = 12;</code>
   */
  public int getStatus() {
    return status_;
  }

  public static final int ADMINFLAG_FIELD_NUMBER = 13;
  private int adminFlag_;
  /**
   * <pre>
   **
   * 是否管理员 0. 普通用户  1. 管理员
   * </pre>
   *
   * <code>int32 adminFlag = 13;</code>
   */
  public int getAdminFlag() {
    return adminFlag_;
  }

  public static final int EXPIRED_FIELD_NUMBER = 14;
  private com.google.protobuf.Timestamp expired_;
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  public boolean hasExpired() {
    return expired_ != null;
  }
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  public com.google.protobuf.Timestamp getExpired() {
    return expired_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expired_;
  }
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getExpiredOrBuilder() {
    return getExpired();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (!getTenantIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantId_);
    }
    if (!getAvatarBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, username_);
    }
    if (!getMobileBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mobile_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, email_);
    }
    if (!getNicknameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nickname_);
    }
    if (!getPasswordBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, password_);
    }
    if (gender_ != 0) {
      output.writeInt32(9, gender_);
    }
    if (userType_ != 0) {
      output.writeInt32(10, userType_);
    }
    if (deptId_ != 0L) {
      output.writeInt64(11, deptId_);
    }
    if (status_ != 0) {
      output.writeInt32(12, status_);
    }
    if (adminFlag_ != 0) {
      output.writeInt32(13, adminFlag_);
    }
    if (expired_ != null) {
      output.writeMessage(14, getExpired());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (!getTenantIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantId_);
    }
    if (!getAvatarBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, username_);
    }
    if (!getMobileBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mobile_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, email_);
    }
    if (!getNicknameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nickname_);
    }
    if (!getPasswordBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, password_);
    }
    if (gender_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, gender_);
    }
    if (userType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, userType_);
    }
    if (deptId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, deptId_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, status_);
    }
    if (adminFlag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, adminFlag_);
    }
    if (expired_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getExpired());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xaaef.grpc.lib.domain.UserInfo)) {
      return super.equals(obj);
    }
    com.xaaef.grpc.lib.domain.UserInfo other = (com.xaaef.grpc.lib.domain.UserInfo) obj;

    boolean result = true;
    result = result && (getUserId()
        == other.getUserId());
    result = result && getTenantId()
        .equals(other.getTenantId());
    result = result && getAvatar()
        .equals(other.getAvatar());
    result = result && getUsername()
        .equals(other.getUsername());
    result = result && getMobile()
        .equals(other.getMobile());
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && getNickname()
        .equals(other.getNickname());
    result = result && getPassword()
        .equals(other.getPassword());
    result = result && (getGender()
        == other.getGender());
    result = result && (getUserType()
        == other.getUserType());
    result = result && (getDeptId()
        == other.getDeptId());
    result = result && (getStatus()
        == other.getStatus());
    result = result && (getAdminFlag()
        == other.getAdminFlag());
    result = result && (hasExpired() == other.hasExpired());
    if (hasExpired()) {
      result = result && getExpired()
          .equals(other.getExpired());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + MOBILE_FIELD_NUMBER;
    hash = (53 * hash) + getMobile().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickname().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + getGender();
    hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getUserType();
    hash = (37 * hash) + DEPTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeptId());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + ADMINFLAG_FIELD_NUMBER;
    hash = (53 * hash) + getAdminFlag();
    if (hasExpired()) {
      hash = (37 * hash) + EXPIRED_FIELD_NUMBER;
      hash = (53 * hash) + getExpired().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xaaef.grpc.lib.domain.UserInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.xaaef.UserInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.xaaef.UserInfo)
      com.xaaef.grpc.lib.domain.UserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xaaef.grpc.lib.domain.UserInfo.class, com.xaaef.grpc.lib.domain.UserInfo.Builder.class);
    }

    // Construct using com.xaaef.grpc.lib.domain.UserInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      tenantId_ = "";

      avatar_ = "";

      username_ = "";

      mobile_ = "";

      email_ = "";

      nickname_ = "";

      password_ = "";

      gender_ = 0;

      userType_ = 0;

      deptId_ = 0L;

      status_ = 0;

      adminFlag_ = 0;

      if (expiredBuilder_ == null) {
        expired_ = null;
      } else {
        expired_ = null;
        expiredBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_com_xaaef_UserInfo_descriptor;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.UserInfo getDefaultInstanceForType() {
      return com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.UserInfo build() {
      com.xaaef.grpc.lib.domain.UserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.UserInfo buildPartial() {
      com.xaaef.grpc.lib.domain.UserInfo result = new com.xaaef.grpc.lib.domain.UserInfo(this);
      result.userId_ = userId_;
      result.tenantId_ = tenantId_;
      result.avatar_ = avatar_;
      result.username_ = username_;
      result.mobile_ = mobile_;
      result.email_ = email_;
      result.nickname_ = nickname_;
      result.password_ = password_;
      result.gender_ = gender_;
      result.userType_ = userType_;
      result.deptId_ = deptId_;
      result.status_ = status_;
      result.adminFlag_ = adminFlag_;
      if (expiredBuilder_ == null) {
        result.expired_ = expired_;
      } else {
        result.expired_ = expiredBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xaaef.grpc.lib.domain.UserInfo) {
        return mergeFrom((com.xaaef.grpc.lib.domain.UserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xaaef.grpc.lib.domain.UserInfo other) {
      if (other == com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getMobile().isEmpty()) {
        mobile_ = other.mobile_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getNickname().isEmpty()) {
        nickname_ = other.nickname_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.getGender() != 0) {
        setGender(other.getGender());
      }
      if (other.getUserType() != 0) {
        setUserType(other.getUserType());
      }
      if (other.getDeptId() != 0L) {
        setDeptId(other.getDeptId());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getAdminFlag() != 0) {
        setAdminFlag(other.getAdminFlag());
      }
      if (other.hasExpired()) {
        mergeExpired(other.getExpired());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.xaaef.grpc.lib.domain.UserInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.xaaef.grpc.lib.domain.UserInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     */
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public Builder clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mobile_ = "";
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public Builder setMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public Builder clearMobile() {
      
      mobile_ = getDefaultInstance().getMobile();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     */
    public Builder setMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mobile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nickname_ = "";
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     */
    public Builder setNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     */
    public Builder clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     */
    public Builder setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nickname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private int gender_ ;
    /**
     * <pre>
     **
     * 性别[ 0.女  1.男  2.未知]
     * </pre>
     *
     * <code>int32 gender = 9;</code>
     */
    public int getGender() {
      return gender_;
    }
    /**
     * <pre>
     **
     * 性别[ 0.女  1.男  2.未知]
     * </pre>
     *
     * <code>int32 gender = 9;</code>
     */
    public Builder setGender(int value) {
      
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 性别[ 0.女  1.男  2.未知]
     * </pre>
     *
     * <code>int32 gender = 9;</code>
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private int userType_ ;
    /**
     * <pre>
     **
     * 用户类型 0.租户用户 1. 系统用户
     * </pre>
     *
     * <code>int32 userType = 10;</code>
     */
    public int getUserType() {
      return userType_;
    }
    /**
     * <pre>
     **
     * 用户类型 0.租户用户 1. 系统用户
     * </pre>
     *
     * <code>int32 userType = 10;</code>
     */
    public Builder setUserType(int value) {
      
      userType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户类型 0.租户用户 1. 系统用户
     * </pre>
     *
     * <code>int32 userType = 10;</code>
     */
    public Builder clearUserType() {
      
      userType_ = 0;
      onChanged();
      return this;
    }

    private long deptId_ ;
    /**
     * <pre>
     **
     * 所属部门
     * </pre>
     *
     * <code>int64 deptId = 11;</code>
     */
    public long getDeptId() {
      return deptId_;
    }
    /**
     * <pre>
     **
     * 所属部门
     * </pre>
     *
     * <code>int64 deptId = 11;</code>
     */
    public Builder setDeptId(long value) {
      
      deptId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 所属部门
     * </pre>
     *
     * <code>int64 deptId = 11;</code>
     */
    public Builder clearDeptId() {
      
      deptId_ = 0L;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <pre>
     **
     * 状态 【0.禁用 1.正常】
     * </pre>
     *
     * <code>int32 status = 12;</code>
     */
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     **
     * 状态 【0.禁用 1.正常】
     * </pre>
     *
     * <code>int32 status = 12;</code>
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 状态 【0.禁用 1.正常】
     * </pre>
     *
     * <code>int32 status = 12;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int adminFlag_ ;
    /**
     * <pre>
     **
     * 是否管理员 0. 普通用户  1. 管理员
     * </pre>
     *
     * <code>int32 adminFlag = 13;</code>
     */
    public int getAdminFlag() {
      return adminFlag_;
    }
    /**
     * <pre>
     **
     * 是否管理员 0. 普通用户  1. 管理员
     * </pre>
     *
     * <code>int32 adminFlag = 13;</code>
     */
    public Builder setAdminFlag(int value) {
      
      adminFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 是否管理员 0. 普通用户  1. 管理员
     * </pre>
     *
     * <code>int32 adminFlag = 13;</code>
     */
    public Builder clearAdminFlag() {
      
      adminFlag_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp expired_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiredBuilder_;
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public boolean hasExpired() {
      return expiredBuilder_ != null || expired_ != null;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public com.google.protobuf.Timestamp getExpired() {
      if (expiredBuilder_ == null) {
        return expired_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expired_;
      } else {
        return expiredBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder setExpired(com.google.protobuf.Timestamp value) {
      if (expiredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expired_ = value;
        onChanged();
      } else {
        expiredBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder setExpired(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiredBuilder_ == null) {
        expired_ = builderForValue.build();
        onChanged();
      } else {
        expiredBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder mergeExpired(com.google.protobuf.Timestamp value) {
      if (expiredBuilder_ == null) {
        if (expired_ != null) {
          expired_ =
            com.google.protobuf.Timestamp.newBuilder(expired_).mergeFrom(value).buildPartial();
        } else {
          expired_ = value;
        }
        onChanged();
      } else {
        expiredBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder clearExpired() {
      if (expiredBuilder_ == null) {
        expired_ = null;
        onChanged();
      } else {
        expired_ = null;
        expiredBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiredBuilder() {
      
      onChanged();
      return getExpiredFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiredOrBuilder() {
      if (expiredBuilder_ != null) {
        return expiredBuilder_.getMessageOrBuilder();
      } else {
        return expired_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expired_;
      }
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiredFieldBuilder() {
      if (expiredBuilder_ == null) {
        expiredBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpired(),
                getParentForChildren(),
                isClean());
        expired_ = null;
      }
      return expiredBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.xaaef.UserInfo)
  }

  // @@protoc_insertion_point(class_scope:com.xaaef.UserInfo)
  private static final com.xaaef.grpc.lib.domain.UserInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xaaef.grpc.lib.domain.UserInfo();
  }

  public static com.xaaef.grpc.lib.domain.UserInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
    @java.lang.Override
    public UserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new UserInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<UserInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xaaef.grpc.lib.domain.UserInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

