// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package com.xaaef.grpc.lib.domain;

/**
 * Protobuf type {@code greet.UserInfo}
 */
public final class UserInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:greet.UserInfo)
    UserInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use UserInfo.newBuilder() to construct.
  private UserInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private UserInfo() {
    tenantId_ = "";
    avatar_ = "";
    username_ = "";
    mobile_ = "";
    email_ = "";
    nickname_ = "";
    password_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new UserInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_UserInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_UserInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.xaaef.grpc.lib.domain.UserInfo.class, com.xaaef.grpc.lib.domain.UserInfo.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int TENANTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object tenantId_;
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The tenantId.
   */
  @java.lang.Override
  public java.lang.String getTenantId() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tenantId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   * @return The bytes for tenantId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTenantIdBytes() {
    java.lang.Object ref = tenantId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tenantId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AVATAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object avatar_;
  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   * @return The avatar.
   */
  @java.lang.Override
  public java.lang.String getAvatar() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      avatar_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   * @return The bytes for avatar.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAvatarBytes() {
    java.lang.Object ref = avatar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      avatar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int USERNAME_FIELD_NUMBER = 4;
  private volatile java.lang.Object username_;
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   * @return The username.
   */
  @java.lang.Override
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   * @return The bytes for username.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MOBILE_FIELD_NUMBER = 5;
  private volatile java.lang.Object mobile_;
  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   * @return The mobile.
   */
  @java.lang.Override
  public java.lang.String getMobile() {
    java.lang.Object ref = mobile_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      mobile_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   * @return The bytes for mobile.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMobileBytes() {
    java.lang.Object ref = mobile_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      mobile_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMAIL_FIELD_NUMBER = 6;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   * @return The email.
   */
  @java.lang.Override
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   * @return The bytes for email.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NICKNAME_FIELD_NUMBER = 7;
  private volatile java.lang.Object nickname_;
  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   * @return The nickname.
   */
  @java.lang.Override
  public java.lang.String getNickname() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nickname_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   * @return The bytes for nickname.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNicknameBytes() {
    java.lang.Object ref = nickname_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nickname_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PASSWORD_FIELD_NUMBER = 8;
  private volatile java.lang.Object password_;
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   * @return The password.
   */
  @java.lang.Override
  public java.lang.String getPassword() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      password_ = s;
      return s;
    }
  }
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   * @return The bytes for password.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPasswordBytes() {
    java.lang.Object ref = password_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      password_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENDER_FIELD_NUMBER = 9;
  private int gender_;
  /**
   * <pre>
   **
   * 性别[ 0.女  1.男  2.未知]
   * </pre>
   *
   * <code>int32 gender = 9;</code>
   * @return The gender.
   */
  @java.lang.Override
  public int getGender() {
    return gender_;
  }

  public static final int USERTYPE_FIELD_NUMBER = 10;
  private int userType_;
  /**
   * <pre>
   **
   * 用户类型 0.租户用户 1. 系统用户
   * </pre>
   *
   * <code>int32 userType = 10;</code>
   * @return The userType.
   */
  @java.lang.Override
  public int getUserType() {
    return userType_;
  }

  public static final int DEPTID_FIELD_NUMBER = 11;
  private long deptId_;
  /**
   * <pre>
   **
   * 所属部门
   * </pre>
   *
   * <code>int64 deptId = 11;</code>
   * @return The deptId.
   */
  @java.lang.Override
  public long getDeptId() {
    return deptId_;
  }

  public static final int STATUS_FIELD_NUMBER = 12;
  private int status_;
  /**
   * <pre>
   **
   * 状态 【0.禁用 1.正常】
   * </pre>
   *
   * <code>int32 status = 12;</code>
   * @return The status.
   */
  @java.lang.Override
  public int getStatus() {
    return status_;
  }

  public static final int ADMINFLAG_FIELD_NUMBER = 13;
  private int adminFlag_;
  /**
   * <pre>
   **
   * 是否管理员 0. 普通用户  1. 管理员
   * </pre>
   *
   * <code>int32 adminFlag = 13;</code>
   * @return The adminFlag.
   */
  @java.lang.Override
  public int getAdminFlag() {
    return adminFlag_;
  }

  public static final int EXPIRED_FIELD_NUMBER = 14;
  private com.google.protobuf.Timestamp expired_;
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   * @return Whether the expired field is set.
   */
  @java.lang.Override
  public boolean hasExpired() {
    return expired_ != null;
  }
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   * @return The expired.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getExpired() {
    return expired_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expired_;
  }
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getExpiredOrBuilder() {
    return getExpired();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, avatar_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, mobile_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nickname_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nickname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, password_);
    }
    if (gender_ != 0) {
      output.writeInt32(9, gender_);
    }
    if (userType_ != 0) {
      output.writeInt32(10, userType_);
    }
    if (deptId_ != 0L) {
      output.writeInt64(11, deptId_);
    }
    if (status_ != 0) {
      output.writeInt32(12, status_);
    }
    if (adminFlag_ != 0) {
      output.writeInt32(13, adminFlag_);
    }
    if (expired_ != null) {
      output.writeMessage(14, getExpired());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(tenantId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, tenantId_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(avatar_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, avatar_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(username_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, username_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(mobile_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, mobile_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(email_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, email_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nickname_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nickname_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(password_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, password_);
    }
    if (gender_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, gender_);
    }
    if (userType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, userType_);
    }
    if (deptId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(11, deptId_);
    }
    if (status_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(12, status_);
    }
    if (adminFlag_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(13, adminFlag_);
    }
    if (expired_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getExpired());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.xaaef.grpc.lib.domain.UserInfo)) {
      return super.equals(obj);
    }
    com.xaaef.grpc.lib.domain.UserInfo other = (com.xaaef.grpc.lib.domain.UserInfo) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (!getTenantId()
        .equals(other.getTenantId())) return false;
    if (!getAvatar()
        .equals(other.getAvatar())) return false;
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getMobile()
        .equals(other.getMobile())) return false;
    if (!getEmail()
        .equals(other.getEmail())) return false;
    if (!getNickname()
        .equals(other.getNickname())) return false;
    if (!getPassword()
        .equals(other.getPassword())) return false;
    if (getGender()
        != other.getGender()) return false;
    if (getUserType()
        != other.getUserType()) return false;
    if (getDeptId()
        != other.getDeptId()) return false;
    if (getStatus()
        != other.getStatus()) return false;
    if (getAdminFlag()
        != other.getAdminFlag()) return false;
    if (hasExpired() != other.hasExpired()) return false;
    if (hasExpired()) {
      if (!getExpired()
          .equals(other.getExpired())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + TENANTID_FIELD_NUMBER;
    hash = (53 * hash) + getTenantId().hashCode();
    hash = (37 * hash) + AVATAR_FIELD_NUMBER;
    hash = (53 * hash) + getAvatar().hashCode();
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    hash = (37 * hash) + MOBILE_FIELD_NUMBER;
    hash = (53 * hash) + getMobile().hashCode();
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
    hash = (53 * hash) + getNickname().hashCode();
    hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
    hash = (53 * hash) + getPassword().hashCode();
    hash = (37 * hash) + GENDER_FIELD_NUMBER;
    hash = (53 * hash) + getGender();
    hash = (37 * hash) + USERTYPE_FIELD_NUMBER;
    hash = (53 * hash) + getUserType();
    hash = (37 * hash) + DEPTID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getDeptId());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStatus();
    hash = (37 * hash) + ADMINFLAG_FIELD_NUMBER;
    hash = (53 * hash) + getAdminFlag();
    if (hasExpired()) {
      hash = (37 * hash) + EXPIRED_FIELD_NUMBER;
      hash = (53 * hash) + getExpired().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.xaaef.grpc.lib.domain.UserInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.xaaef.grpc.lib.domain.UserInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code greet.UserInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:greet.UserInfo)
      com.xaaef.grpc.lib.domain.UserInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_UserInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.xaaef.grpc.lib.domain.UserInfo.class, com.xaaef.grpc.lib.domain.UserInfo.Builder.class);
    }

    // Construct using com.xaaef.grpc.lib.domain.UserInfo.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      tenantId_ = "";

      avatar_ = "";

      username_ = "";

      mobile_ = "";

      email_ = "";

      nickname_ = "";

      password_ = "";

      gender_ = 0;

      userType_ = 0;

      deptId_ = 0L;

      status_ = 0;

      adminFlag_ = 0;

      if (expiredBuilder_ == null) {
        expired_ = null;
      } else {
        expired_ = null;
        expiredBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.xaaef.grpc.lib.domain.Domain.internal_static_greet_UserInfo_descriptor;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.UserInfo getDefaultInstanceForType() {
      return com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.UserInfo build() {
      com.xaaef.grpc.lib.domain.UserInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.xaaef.grpc.lib.domain.UserInfo buildPartial() {
      com.xaaef.grpc.lib.domain.UserInfo result = new com.xaaef.grpc.lib.domain.UserInfo(this);
      result.userId_ = userId_;
      result.tenantId_ = tenantId_;
      result.avatar_ = avatar_;
      result.username_ = username_;
      result.mobile_ = mobile_;
      result.email_ = email_;
      result.nickname_ = nickname_;
      result.password_ = password_;
      result.gender_ = gender_;
      result.userType_ = userType_;
      result.deptId_ = deptId_;
      result.status_ = status_;
      result.adminFlag_ = adminFlag_;
      if (expiredBuilder_ == null) {
        result.expired_ = expired_;
      } else {
        result.expired_ = expiredBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.xaaef.grpc.lib.domain.UserInfo) {
        return mergeFrom((com.xaaef.grpc.lib.domain.UserInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.xaaef.grpc.lib.domain.UserInfo other) {
      if (other == com.xaaef.grpc.lib.domain.UserInfo.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (!other.getTenantId().isEmpty()) {
        tenantId_ = other.tenantId_;
        onChanged();
      }
      if (!other.getAvatar().isEmpty()) {
        avatar_ = other.avatar_;
        onChanged();
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.getMobile().isEmpty()) {
        mobile_ = other.mobile_;
        onChanged();
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getNickname().isEmpty()) {
        nickname_ = other.nickname_;
        onChanged();
      }
      if (!other.getPassword().isEmpty()) {
        password_ = other.password_;
        onChanged();
      }
      if (other.getGender() != 0) {
        setGender(other.getGender());
      }
      if (other.getUserType() != 0) {
        setUserType(other.getUserType());
      }
      if (other.getDeptId() != 0L) {
        setDeptId(other.getDeptId());
      }
      if (other.getStatus() != 0) {
        setStatus(other.getStatus());
      }
      if (other.getAdminFlag() != 0) {
        setAdminFlag(other.getAdminFlag());
      }
      if (other.hasExpired()) {
        mergeExpired(other.getExpired());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              userId_ = input.readInt64();

              break;
            } // case 8
            case 18: {
              tenantId_ = input.readStringRequireUtf8();

              break;
            } // case 18
            case 26: {
              avatar_ = input.readStringRequireUtf8();

              break;
            } // case 26
            case 34: {
              username_ = input.readStringRequireUtf8();

              break;
            } // case 34
            case 42: {
              mobile_ = input.readStringRequireUtf8();

              break;
            } // case 42
            case 50: {
              email_ = input.readStringRequireUtf8();

              break;
            } // case 50
            case 58: {
              nickname_ = input.readStringRequireUtf8();

              break;
            } // case 58
            case 66: {
              password_ = input.readStringRequireUtf8();

              break;
            } // case 66
            case 72: {
              gender_ = input.readInt32();

              break;
            } // case 72
            case 80: {
              userType_ = input.readInt32();

              break;
            } // case 80
            case 88: {
              deptId_ = input.readInt64();

              break;
            } // case 88
            case 96: {
              status_ = input.readInt32();

              break;
            } // case 96
            case 104: {
              adminFlag_ = input.readInt32();

              break;
            } // case 104
            case 114: {
              input.readMessage(
                  getExpiredFieldBuilder().getBuilder(),
                  extensionRegistry);

              break;
            } // case 114
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private long userId_ ;
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户ID
     * </pre>
     *
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object tenantId_ = "";
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     * @return The tenantId.
     */
    public java.lang.String getTenantId() {
      java.lang.Object ref = tenantId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tenantId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     * @return The bytes for tenantId.
     */
    public com.google.protobuf.ByteString
        getTenantIdBytes() {
      java.lang.Object ref = tenantId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tenantId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     * @param value The tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tenantId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTenantId() {
      
      tenantId_ = getDefaultInstance().getTenantId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 租户ID
     * </pre>
     *
     * <code>string tenantId = 2;</code>
     * @param value The bytes for tenantId to set.
     * @return This builder for chaining.
     */
    public Builder setTenantIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tenantId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object avatar_ = "";
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The avatar.
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return The bytes for avatar.
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @param value The avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      avatar_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearAvatar() {
      
      avatar_ = getDefaultInstance().getAvatar();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 头像
     * </pre>
     *
     * <code>string avatar = 3;</code>
     * @param value The bytes for avatar to set.
     * @return This builder for chaining.
     */
    public Builder setAvatarBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      avatar_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object username_ = "";
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     * @return The username.
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     * @param value The username to set.
     * @return This builder for chaining.
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名
     * </pre>
     *
     * <code>string username = 4;</code>
     * @param value The bytes for username to set.
     * @return This builder for chaining.
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object mobile_ = "";
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     * @return The mobile.
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     * @return The bytes for mobile.
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     * @param value The mobile to set.
     * @return This builder for chaining.
     */
    public Builder setMobile(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      mobile_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMobile() {
      
      mobile_ = getDefaultInstance().getMobile();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 手机号
     * </pre>
     *
     * <code>string mobile = 5;</code>
     * @param value The bytes for mobile to set.
     * @return This builder for chaining.
     */
    public Builder setMobileBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      mobile_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     * @param value The email to set.
     * @return This builder for chaining.
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 邮箱
     * </pre>
     *
     * <code>string email = 6;</code>
     * @param value The bytes for email to set.
     * @return This builder for chaining.
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object nickname_ = "";
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     * @return The nickname.
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickname_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     * @return The bytes for nickname.
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     * @param value The nickname to set.
     * @return This builder for chaining.
     */
    public Builder setNickname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      nickname_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearNickname() {
      
      nickname_ = getDefaultInstance().getNickname();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户名称
     * </pre>
     *
     * <code>string nickname = 7;</code>
     * @param value The bytes for nickname to set.
     * @return This builder for chaining.
     */
    public Builder setNicknameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      nickname_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object password_ = "";
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     * @return The password.
     */
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     * @return The bytes for password.
     */
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     * @param value The password to set.
     * @return This builder for chaining.
     */
    public Builder setPassword(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      password_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 密码
     * </pre>
     *
     * <code>string password = 8;</code>
     * @param value The bytes for password to set.
     * @return This builder for chaining.
     */
    public Builder setPasswordBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      password_ = value;
      onChanged();
      return this;
    }

    private int gender_ ;
    /**
     * <pre>
     **
     * 性别[ 0.女  1.男  2.未知]
     * </pre>
     *
     * <code>int32 gender = 9;</code>
     * @return The gender.
     */
    @java.lang.Override
    public int getGender() {
      return gender_;
    }
    /**
     * <pre>
     **
     * 性别[ 0.女  1.男  2.未知]
     * </pre>
     *
     * <code>int32 gender = 9;</code>
     * @param value The gender to set.
     * @return This builder for chaining.
     */
    public Builder setGender(int value) {
      
      gender_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 性别[ 0.女  1.男  2.未知]
     * </pre>
     *
     * <code>int32 gender = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearGender() {
      
      gender_ = 0;
      onChanged();
      return this;
    }

    private int userType_ ;
    /**
     * <pre>
     **
     * 用户类型 0.租户用户 1. 系统用户
     * </pre>
     *
     * <code>int32 userType = 10;</code>
     * @return The userType.
     */
    @java.lang.Override
    public int getUserType() {
      return userType_;
    }
    /**
     * <pre>
     **
     * 用户类型 0.租户用户 1. 系统用户
     * </pre>
     *
     * <code>int32 userType = 10;</code>
     * @param value The userType to set.
     * @return This builder for chaining.
     */
    public Builder setUserType(int value) {
      
      userType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 用户类型 0.租户用户 1. 系统用户
     * </pre>
     *
     * <code>int32 userType = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserType() {
      
      userType_ = 0;
      onChanged();
      return this;
    }

    private long deptId_ ;
    /**
     * <pre>
     **
     * 所属部门
     * </pre>
     *
     * <code>int64 deptId = 11;</code>
     * @return The deptId.
     */
    @java.lang.Override
    public long getDeptId() {
      return deptId_;
    }
    /**
     * <pre>
     **
     * 所属部门
     * </pre>
     *
     * <code>int64 deptId = 11;</code>
     * @param value The deptId to set.
     * @return This builder for chaining.
     */
    public Builder setDeptId(long value) {
      
      deptId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 所属部门
     * </pre>
     *
     * <code>int64 deptId = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeptId() {
      
      deptId_ = 0L;
      onChanged();
      return this;
    }

    private int status_ ;
    /**
     * <pre>
     **
     * 状态 【0.禁用 1.正常】
     * </pre>
     *
     * <code>int32 status = 12;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }
    /**
     * <pre>
     **
     * 状态 【0.禁用 1.正常】
     * </pre>
     *
     * <code>int32 status = 12;</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(int value) {
      
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 状态 【0.禁用 1.正常】
     * </pre>
     *
     * <code>int32 status = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private int adminFlag_ ;
    /**
     * <pre>
     **
     * 是否管理员 0. 普通用户  1. 管理员
     * </pre>
     *
     * <code>int32 adminFlag = 13;</code>
     * @return The adminFlag.
     */
    @java.lang.Override
    public int getAdminFlag() {
      return adminFlag_;
    }
    /**
     * <pre>
     **
     * 是否管理员 0. 普通用户  1. 管理员
     * </pre>
     *
     * <code>int32 adminFlag = 13;</code>
     * @param value The adminFlag to set.
     * @return This builder for chaining.
     */
    public Builder setAdminFlag(int value) {
      
      adminFlag_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     **
     * 是否管理员 0. 普通用户  1. 管理员
     * </pre>
     *
     * <code>int32 adminFlag = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearAdminFlag() {
      
      adminFlag_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp expired_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> expiredBuilder_;
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     * @return Whether the expired field is set.
     */
    public boolean hasExpired() {
      return expiredBuilder_ != null || expired_ != null;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     * @return The expired.
     */
    public com.google.protobuf.Timestamp getExpired() {
      if (expiredBuilder_ == null) {
        return expired_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : expired_;
      } else {
        return expiredBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder setExpired(com.google.protobuf.Timestamp value) {
      if (expiredBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        expired_ = value;
        onChanged();
      } else {
        expiredBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder setExpired(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (expiredBuilder_ == null) {
        expired_ = builderForValue.build();
        onChanged();
      } else {
        expiredBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder mergeExpired(com.google.protobuf.Timestamp value) {
      if (expiredBuilder_ == null) {
        if (expired_ != null) {
          expired_ =
            com.google.protobuf.Timestamp.newBuilder(expired_).mergeFrom(value).buildPartial();
        } else {
          expired_ = value;
        }
        onChanged();
      } else {
        expiredBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public Builder clearExpired() {
      if (expiredBuilder_ == null) {
        expired_ = null;
        onChanged();
      } else {
        expired_ = null;
        expiredBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public com.google.protobuf.Timestamp.Builder getExpiredBuilder() {
      
      onChanged();
      return getExpiredFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getExpiredOrBuilder() {
      if (expiredBuilder_ != null) {
        return expiredBuilder_.getMessageOrBuilder();
      } else {
        return expired_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : expired_;
      }
    }
    /**
     * <pre>
     **
     * 过期时间  为空就是永久
     * </pre>
     *
     * <code>.google.protobuf.Timestamp expired = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getExpiredFieldBuilder() {
      if (expiredBuilder_ == null) {
        expiredBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getExpired(),
                getParentForChildren(),
                isClean());
        expired_ = null;
      }
      return expiredBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:greet.UserInfo)
  }

  // @@protoc_insertion_point(class_scope:greet.UserInfo)
  private static final com.xaaef.grpc.lib.domain.UserInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.xaaef.grpc.lib.domain.UserInfo();
  }

  public static com.xaaef.grpc.lib.domain.UserInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<UserInfo>
      PARSER = new com.google.protobuf.AbstractParser<UserInfo>() {
    @java.lang.Override
    public UserInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<UserInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<UserInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.xaaef.grpc.lib.domain.UserInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

