// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: domain.proto

package com.xaaef.grpc.lib.domain;

public interface UserInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:greet.UserInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   **
   * 用户ID
   * </pre>
   *
   * <code>int64 userId = 1;</code>
   */
  long getUserId();

  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   */
  java.lang.String getTenantId();
  /**
   * <pre>
   **
   * 租户ID
   * </pre>
   *
   * <code>string tenantId = 2;</code>
   */
  com.google.protobuf.ByteString
      getTenantIdBytes();

  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  java.lang.String getAvatar();
  /**
   * <pre>
   **
   * 头像
   * </pre>
   *
   * <code>string avatar = 3;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();

  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   */
  java.lang.String getUsername();
  /**
   * <pre>
   **
   * 用户名
   * </pre>
   *
   * <code>string username = 4;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   */
  java.lang.String getMobile();
  /**
   * <pre>
   **
   * 手机号
   * </pre>
   *
   * <code>string mobile = 5;</code>
   */
  com.google.protobuf.ByteString
      getMobileBytes();

  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   */
  java.lang.String getEmail();
  /**
   * <pre>
   **
   * 邮箱
   * </pre>
   *
   * <code>string email = 6;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   */
  java.lang.String getNickname();
  /**
   * <pre>
   **
   * 用户名称
   * </pre>
   *
   * <code>string nickname = 7;</code>
   */
  com.google.protobuf.ByteString
      getNicknameBytes();

  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   **
   * 密码
   * </pre>
   *
   * <code>string password = 8;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <pre>
   **
   * 性别[ 0.女  1.男  2.未知]
   * </pre>
   *
   * <code>int32 gender = 9;</code>
   */
  int getGender();

  /**
   * <pre>
   **
   * 用户类型 0.租户用户 1. 系统用户
   * </pre>
   *
   * <code>int32 userType = 10;</code>
   */
  int getUserType();

  /**
   * <pre>
   **
   * 所属部门
   * </pre>
   *
   * <code>int64 deptId = 11;</code>
   */
  long getDeptId();

  /**
   * <pre>
   **
   * 状态 【0.禁用 1.正常】
   * </pre>
   *
   * <code>int32 status = 12;</code>
   */
  int getStatus();

  /**
   * <pre>
   **
   * 是否管理员 0. 普通用户  1. 管理员
   * </pre>
   *
   * <code>int32 adminFlag = 13;</code>
   */
  int getAdminFlag();

  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  boolean hasExpired();
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  com.google.protobuf.Timestamp getExpired();
  /**
   * <pre>
   **
   * 过期时间  为空就是永久
   * </pre>
   *
   * <code>.google.protobuf.Timestamp expired = 14;</code>
   */
  com.google.protobuf.TimestampOrBuilder getExpiredOrBuilder();
}
