// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package com.xaaef.grpc.lib.config;

public final class ConfigOuterClass {
  private ConfigOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\022\tcom.xaaef\032\037google/protob" +
      "uf/timestamp.proto\032\036google/protobuf/wrap" +
      "pers.proto2\355\001\n\006Config\022L\n\016GetStringValue\022" +
      "\034.google.protobuf.StringValue\032\034.google.p" +
      "rotobuf.StringValue\022H\n\014GetBoolValue\022\034.go" +
      "ogle.protobuf.StringValue\032\032.google.proto" +
      "buf.BoolValue\022K\n\016GetNumberValue\022\034.google" +
      ".protobuf.StringValue\032\033.google.protobuf." +
      "Int64ValueB7\n\031com.xaaef.grpc.lib.configP" +
      "\001Z\t.;message\252\002\014GrpcService1P\000P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
        }, assigner);
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
