// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.xaaef.grpc.lib.greet;

public final class Greet {
  private Greet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xaaef_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xaaef_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xaaef_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_xaaef_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013greet.proto\022\tcom.xaaef\032\037google/protobu" +
      "f/timestamp.proto\032\036google/protobuf/wrapp" +
      "ers.proto\032\014domain.proto\"\034\n\014HelloRequest\022" +
      "\014\n\004name\030\001 \001(\t\"\035\n\nHelloReply\022\017\n\007message\030\001" +
      " \001(\t2\207\001\n\007Greeter\022:\n\010SayHello\022\027.com.xaaef" +
      ".HelloRequest\032\025.com.xaaef.HelloReply\022@\n\013" +
      "GetUserInfo\022\034.google.protobuf.StringValu" +
      "e\032\023.com.xaaef.UserInfoB6\n\030com.xaaef.grpc" +
      ".lib.greetP\001Z\t.;message\252\002\014GrpcService1P\000" +
      "P\001P\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.xaaef.grpc.lib.domain.Domain.getDescriptor(),
        });
    internal_static_com_xaaef_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_xaaef_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xaaef_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_xaaef_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_xaaef_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_xaaef_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.xaaef.grpc.lib.domain.Domain.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
