// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greet.proto

package com.xaaef.grpc.lib.greet;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.xaaef.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
