## 断路器 配置
resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      slow-call-duration-threshold: 2s
      failureRateThreshold: 30
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - io.grpc.StatusRuntimeException
        - java.lang.RuntimeException
        - java.io.IOException


## 超时配置
resilience4j.timelimiter:
  configs:
    default:
      timeout-duration: 1s
      cancel-running-future: true


## 重试配置
resilience4j.retry:
  configs:
    default:
      max-attempts: 2
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - io.grpc.StatusRuntimeException
        - java.lang.RuntimeException
        - java.io.IOException



## 限流配置
resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      eventConsumerBufferSize: 100


## 舱壁配置
resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 100


## 舱壁线程池配置
resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2
