resilience4j.circuitbreaker:
  circuit-breaker-aspect-order: 1
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 30
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - io.grpc.StatusRuntimeException
        - java.lang.RuntimeException
        - java.io.IOException



resilience4j.retry:
  retry-aspect-order: 2
  configs:
    default:
      maxRetryAttempts: 2
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - io.grpc.StatusRuntimeException
        - java.lang.RuntimeException
        - java.io.IOException


resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 100


resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 4
      coreThreadPoolSize: 2
      queueCapacity: 2


resilience4j.ratelimiter:
  rate-limiter-aspect-order: 5
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 10
      limitRefreshPeriod: 1s
      timeoutDuration: 0
      eventConsumerBufferSize: 100
