server:
  port: 18030

spring:
  application:
    name: grpc-client
  profiles:
    include: resilience4j
    active: dev
  threads:
    virtual:
      enabled: true


# Grpc配置
grpc:
  server:
    port: 18031
  client:
    GLOBAL:
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true
    cshap-grpc:
      address: static://localhost:18011


info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 0.0.1


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


