server:
  port: 18189

spring:
  application:
    name: grpc-client


  cloud:
    consul:
      host: ${REGISTER_SERVER_HOST:127.0.0.1}
      port: ${REGISTER_SERVER_PORT:8500}
      discovery:
        prefer-ip-address: true



resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 10
      waitDurationInOpenState: 10000
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      registerHealthIndicator: true
    someShared:
      slidingWindowSize: 50
      permittedNumberOfCallsInHalfOpenState: 10
  instances:
    sayHello:
      baseConfig: default
      waitDurationInOpenState: 5000
    backendB:
      baseConfig: someShared




# Grpc配置
grpc:
  client:
    GLOBAL:
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true



info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


