server:
  port: 18030

spring:
  application:
    name: grpc-client
  profiles:
    include: resilience4j


  cloud:
    consul:
      host: ${REGISTER_SERVER_HOST:127.0.0.1}
      port: ${REGISTER_SERVER_PORT:8500}
      discovery:
        prefer-ip-address: true


# Grpc配置
grpc:
  server:
    port: 18031
  client:
    GLOBAL:
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true
    grpc-demo1:
      address: static://localhost:5016
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-without-calls: true


info:
  app:
    name: ${spring.application.name}
    description: ${spring.application.name}
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS


